# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class TestServiceStub(object):
    """service SearchService {
    rpc request(RequestMsg) returns (ResponseMsg){}
    }

    message RequestMsg {
    string appId = 1;
    string appName = 2;
    string inputParms = 3;
    //  repeated Result result = 4;
    }

    message ResponseMsg {
    string appId = 1;
    string appName = 2;
    string resBody = 3;
    //  repeated Result result = 4;
    }

    message Result {
    string statusName = 1;
    int32 statusCode = 2;
    }

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.method = channel.unary_unary(
                '/example.TestService/method',
                request_serializer=data__pb2.Request.SerializeToString,
                response_deserializer=data__pb2.Result.FromString,
                )


class TestServiceServicer(object):
    """service SearchService {
    rpc request(RequestMsg) returns (ResponseMsg){}
    }

    message RequestMsg {
    string appId = 1;
    string appName = 2;
    string inputParms = 3;
    //  repeated Result result = 4;
    }

    message ResponseMsg {
    string appId = 1;
    string appName = 2;
    string resBody = 3;
    //  repeated Result result = 4;
    }

    message Result {
    string statusName = 1;
    int32 statusCode = 2;
    }

    """

    def method(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'method': grpc.unary_unary_rpc_method_handler(
                    servicer.method,
                    request_deserializer=data__pb2.Request.FromString,
                    response_serializer=data__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """service SearchService {
    rpc request(RequestMsg) returns (ResponseMsg){}
    }

    message RequestMsg {
    string appId = 1;
    string appName = 2;
    string inputParms = 3;
    //  repeated Result result = 4;
    }

    message ResponseMsg {
    string appId = 1;
    string appName = 2;
    string resBody = 3;
    //  repeated Result result = 4;
    }

    message Result {
    string statusName = 1;
    int32 statusCode = 2;
    }

    """

    @staticmethod
    def method(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.TestService/method',
            data__pb2.Request.SerializeToString,
            data__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
